import { mapModelName } from "../utils/mapperUtils";
import ParallelCoordinatesChart from "./general/ParallelCoordinates";
import PopUp from "./general/PopUp";

function ResultDetailsPopUp({ isOpen, onClose, prediction, confidence, features, usedModel }) {
    function convertValuesToReadable(value) {
        if (value === false) return "No";
        if (value === true) return "Yes";
        return value;
    }

    function toPercents(value) {
        console.log(value);
        return `${(value * 100).toFixed(6)}%`;
    }

    return prediction && features ? (
        <PopUp isOpen={isOpen} onClose={onClose}>
            <h1 className="text-2xl font-bold mb-4">
                This website is a <strong>{prediction}</strong> website!
            </h1>
            <p className="text-lg">
                The {mapModelName(usedModel)} model is <strong>{toPercents(confidence)}</strong>{" "}
                confident that the provided url belongs to a <strong>{prediction}</strong> website.
            </p>
            <p>
                The following information was extracted from the url and the html code of the
                website:
            </p>
            <br />
            {Object.entries(features).map(([key, value]) => (
                <div key={key} className="flex flex-row justify-between">
                    <p className="text-lg">{key}</p>
                    <p className="text-lg">{convertValuesToReadable(value)}</p>
                </div>
            ))}
            <ParallelCoordinatesChart
                listOfTrainingData={[
                    {
                        test: 1,
                        test2: 2,
                        test3: 2,
                        test4: 1,
                        label: 0,
                        attr1: 3,
                        attr2: 4,
                        attr3: 5,
                        attr4: 6,
                        attr5: 7,
                        attr6: 8,
                        attr7: 9,
                        attr8: 10,
                        attr9: 11,
                        attr10: 12,
                        attr11: 13,
                        attr12: 14,
                        attr13: 15,
                        attr14: 16,
                        attr15: 17,
                        attr16: 18,
                        attr17: 19,
                        attr18: 20,
                        attr19: 21,
                        attr20: 22,
                        attr21: 23,
                        attr22: 24,
                        attr23: 25,
                        attr24: 26,
                        attr25: 27,
                        attr26: 28,
                        attr27: 29,
                        attr28: 30,
                        attr29: 31,
                        attr30: 32,
                    },
                    {
                        test: 2,
                        test2: 3,
                        test3: 3,
                        test4: 5,
                        label: 1,
                        attr1: 13,
                        attr2: 14,
                        attr3: 15,
                        attr4: 16,
                        attr5: 17,
                        attr6: 18,
                        attr7: 19,
                        attr8: 20,
                        attr9: 21,
                        attr10: 22,
                        attr11: 23,
                        attr12: 24,
                        attr13: 25,
                        attr14: 26,
                        attr15: 27,
                        attr16: 28,
                        attr17: 29,
                        attr18: 30,
                        attr19: 31,
                        attr20: 32,
                        attr21: 33,
                        attr22: 34,
                        attr23: 35,
                        attr24: 36,
                        attr25: 37,
                        attr26: 38,
                        attr27: 39,
                        attr28: 40,
                        attr29: 41,
                        attr30: 42,
                    },
                    {
                        test: 3,
                        test2: 4,
                        test3: 1,
                        test4: 20,
                        label: 0,
                        attr1: 23,
                        attr2: 24,
                        attr3: 25,
                        attr4: 26,
                        attr5: 27,
                        attr6: 28,
                        attr7: 29,
                        attr8: 30,
                        attr9: 31,
                        attr10: 32,
                        attr11: 33,
                        attr12: 34,
                        attr13: 35,
                        attr14: 36,
                        attr15: 37,
                        attr16: 38,
                        attr17: 39,
                        attr18: 40,
                        attr19: 41,
                        attr20: 42,
                        attr21: 43,
                        attr22: 44,
                        attr23: 45,
                        attr24: 46,
                        attr25: 47,
                        attr26: 48,
                        attr27: 49,
                        attr28: 50,
                        attr29: 51,
                        attr30: 52,
                    },
                    {
                        test: 4,
                        test2: 5,
                        test3: 1,
                        test4: 10,
                        label: 1,
                        attr1: 33,
                        attr2: 34,
                        attr3: 35,
                        attr4: 36,
                        attr5: 37,
                        attr6: 38,
                        attr7: 39,
                        attr8: 40,
                        attr9: 41,
                        attr10: 42,
                        attr11: 43,
                        attr12: 44,
                        attr13: 45,
                        attr14: 46,
                        attr15: 47,
                        attr16: 48,
                        attr17: 49,
                        attr18: 50,
                        attr19: 51,
                        attr20: 52,
                        attr21: 53,
                        attr22: 54,
                        attr23: 55,
                        attr24: 56,
                        attr25: 57,
                        attr26: 58,
                        attr27: 59,
                        attr28: 60,
                        attr29: 61,
                        attr30: 62,
                    },
                    {
                        test: 5,
                        test2: 6,
                        test3: 2,
                        test4: 15,
                        label: 0,
                        attr1: 43,
                        attr2: 44,
                        attr3: 45,
                        attr4: 46,
                        attr5: 47,
                        attr6: 48,
                        attr7: 49,
                        attr8: 50,
                        attr9: 51,
                        attr10: 52,
                        attr11: 53,
                        attr12: 54,
                        attr13: 55,
                        attr14: 56,
                        attr15: 57,
                        attr16: 58,
                        attr17: 59,
                        attr18: 60,
                        attr19: 61,
                        attr20: 62,
                        attr21: 63,
                        attr22: 64,
                        attr23: 65,
                        attr24: 66,
                        attr25: 67,
                        attr26: 68,
                        attr27: 69,
                        attr28: 70,
                        attr29: 71,
                        attr30: 72,
                    },
                    {
                        test: 6,
                        test2: 7,
                        test3: 1,
                        test4: 30,
                        label: 1,
                        attr1: 53,
                        attr2: 54,
                        attr3: 55,
                        attr4: 56,
                        attr5: 57,
                        attr6: 58,
                        attr7: 59,
                        attr8: 60,
                        attr9: 61,
                        attr10: 62,
                        attr11: 63,
                        attr12: 64,
                        attr13: 65,
                        attr14: 66,
                        attr15: 67,
                        attr16: 68,
                        attr17: 69,
                        attr18: 70,
                        attr19: 71,
                        attr20: 72,
                        attr21: 73,
                        attr22: 74,
                        attr23: 75,
                        attr24: 76,
                        attr25: 77,
                        attr26: 78,
                        attr27: 79,
                        attr28: 80,
                        attr29: 81,
                        attr30: 82,
                    },
                ]}
                listOfCurrData={{
                    test: Math.floor(Math.random() * 70) + 1,
                    test2: Math.floor(Math.random() * 70) + 1,
                    test3: Math.floor(Math.random() * 70) + 1,
                    test4: Math.floor(Math.random() * 70) + 1,
                    label: Math.floor(Math.random() * 2),
                    attr1: Math.floor(Math.random() * 70) + 1,
                    attr2: Math.floor(Math.random() * 70) + 1,
                    attr3: Math.floor(Math.random() * 70) + 1,
                    attr4: Math.floor(Math.random() * 70) + 1,
                    attr5: Math.floor(Math.random() * 70) + 1,
                    attr6: Math.floor(Math.random() * 70) + 1,
                    attr7: Math.floor(Math.random() * 70) + 1,
                    attr8: Math.floor(Math.random() * 70) + 1,
                    attr9: Math.floor(Math.random() * 70) + 1,
                    attr10: Math.floor(Math.random() * 70) + 1,
                    attr11: Math.floor(Math.random() * 70) + 1,
                    attr12: Math.floor(Math.random() * 70) + 1,
                    attr13: Math.floor(Math.random() * 70) + 1,
                    attr14: Math.floor(Math.random() * 70) + 1,
                    attr15: Math.floor(Math.random() * 70) + 1,
                    attr16: Math.floor(Math.random() * 70) + 1,
                    attr17: Math.floor(Math.random() * 70) + 1,
                    attr18: Math.floor(Math.random() * 70) + 1,
                    attr19: Math.floor(Math.random() * 70) + 1,
                    attr20: Math.floor(Math.random() * 70) + 1,
                    attr21: Math.floor(Math.random() * 70) + 1,
                    attr22: Math.floor(Math.random() * 70) + 1,
                    attr23: Math.floor(Math.random() * 70) + 1,
                    attr24: Math.floor(Math.random() * 70) + 1,
                    attr25: Math.floor(Math.random() * 70) + 1,
                    attr26: Math.floor(Math.random() * 70) + 1,
                    attr27: Math.floor(Math.random() * 70) + 1,
                    attr28: Math.floor(Math.random() * 70) + 1,
                    attr29: Math.floor(Math.random() * 70) + 1,
                    attr30: Math.floor(Math.random() * 70) + 1,
                }}
            />
        </PopUp>
    ) : null;
}

export default ResultDetailsPopUp;
